name: athlete_dashboard
description: Premium Athlete Dashboard Application.

# Mencegah aplikasi terpublish tidak sengaja ke pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Package untuk splash screen native awal
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Package untuk mengganti icon aplikasi
  flutter_launcher_icons: ^0.13.1
  flutter_launcher_name: ^0.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  
  # Mendaftarkan folder assets agar splash.png bisa dipanggil manual di main.dart
  assets:
    - assets/

# ==========================================
# KONFIGURASI ICON APLIKASI
# ==========================================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# ==========================================
# KONFIGURASI NATIVE SPLASH SCREEN
# ==========================================
flutter_native_splash:
  color: "#0F172A"
  image: "assets/splash.png"
  android: true
  ios: true
  android_12:
    image: "assets/splash.png"
    color: "#0F172A"
# ==========================================
#       UBAH NAMA APLIKASIMU
# ==========================================
flutter_launcher_name:
  name: "Arena Beladiri"
