name: Build
on:
  push:
    branches: [main, master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - name: Repair Missing Android Files
      run: flutter create . --platforms=android
    - name: Set Android App Name
      run: |
        dart run rename setAppName \
        --value "Arena Beladiri" \
        --targets android
    - name: Set Android Bundle ID
      run: |
        dart run rename setBundleId \
        --value "com.bskrwingchun.hpki" \
        --targets android
    - run: |
        dart run \
        flutter_launcher_icons
    - run: |
        dart run \
        flutter_native_splash:create
    - run: flutter build apk --release
    - run: |
        cd build/app/outputs/flutter-apk
        cp app-release.apk $GITHUB_WORKSPACE
    - uses: actions/upload-artifact@v4
      with:
        name: Arena-Beladiri-APK
        path: app-release.apk
